import { msg } from "@lingui/core/macro";
import type { MessageDescriptor } from "@lingui/core";
import type { ToolParams } from "../../lib/types";

/**
 * What each tool is called, in the user's language. The host sends the tool's name and the
 * values it was asked for; the sentence on the consent card is written here — never by the host,
 * which does not know the language, and never by the model, which must not write the label on a
 * button the user is about to press (`ai/consent.rs`).
 *
 * A tool with no entry still shows its name rather than a blank card: a catalogue that grew
 * faster than this table is a missing translation, not a reason to hide what is being asked.
 */
export const TOOL_LABELS: Record<string, MessageDescriptor> = {
  portfolio_overview: msg`what the portfolio is worth`,
  portfolio_performance: msg`how the portfolio performed`,
  portfolio_breakdown: msg`how the result adds up, step by step`,
  portfolio_risk: msg`volatility and drawdown`,
  positions_list: msg`the instruments you hold`,
  accounts_list: msg`your accounts and cash`,
  allocation_trees: msg`your classification trees`,
  allocation_breakdown: msg`how the portfolio is allocated`,
  income_summary: msg`dividends and interest received`,
  transactions_list: msg`your transactions`,
  securities_find: msg`an instrument in your list`,
  securities_events: msg`an instrument's dividends and splits`,
  market_quotes: msg`how an instrument's price moved`,
  plans_list: msg`your investment plans`,
  plans_projection: msg`what your plans will contribute`,
  alerts_list: msg`your price alerts`,
  alerts_crossings: msg`the alerts that fired`,
  watchlists_list: msg`your watchlists`,
  watchlist_rows: msg`a watchlist and its prices`,
  allocation_members: msg`what is inside one branch`,
  rebalance_targets: msg`your target allocations`,
  rebalance_plan: msg`how far you have drifted from a target`,
  report_capital_gains: msg`what selling realised`,
  report_charges: msg`the fees and taxes you paid`,
  report_trades: msg`your trading over a period`,
  report_summary: msg`this period against the one before`,
  portfolio_benchmark: msg`your return against an instrument's`,
  positions_returns: msg`what each instrument earned`,
  income_calendar: msg`when your income arrived`,
  income_breakdown: msg`which categories your income came from`,
  taxonomy_tree: msg`the branches of a tree`,
  account_groups_list: msg`your account groups`,
  plans_due: msg`the contributions a plan owes`,
  transaction_create: msg`record an operation in your ledger`,
  plan_commit: msg`record a contribution your plan owes`,
  watchlist_set: msg`what a watchlist holds`,
  taxonomy_assign: msg`file an instrument under a branch`,
  alert_delete: msg`remove a price alert`,
  security_set_data_source: msg`where an instrument's prices come from`,
  security_set_note: msg`your note on an instrument`,
  alert_create: msg`a new price alert`,
  transaction_update: msg`correct an operation in your ledger`,
  transaction_delete: msg`remove an operation from your ledger`,
  security_create: msg`add an instrument to your list`,
  security_delete: msg`remove an instrument from your list`,
  security_set_listing: msg`which venue an instrument follows`,
  security_note_add: msg`a dated note on an instrument`,
  security_note_delete: msg`remove your note from an instrument`,
  account_create: msg`open an account`,
  account_update: msg`change an account`,
  account_delete: msg`delete an account`,
  account_group_set: msg`what an account group holds`,
  account_group_delete: msg`delete an account group`,
  plan_save: msg`an investment plan`,
  plan_delete: msg`delete an investment plan`,
  watchlist_delete: msg`delete a watchlist`,
  taxonomy_create: msg`a new classification tree`,
  taxonomy_delete: msg`delete a classification tree`,
  taxonomy_node_add: msg`add a branch to a tree`,
  taxonomy_node_delete: msg`remove a branch from a tree`,
  taxonomy_unassign: msg`take an instrument out of a branch`,
  taxonomy_exclude: msg`switch something off for one tree`,
  rebalance_target_save: msg`a target allocation`,
  rebalance_target_delete: msg`delete a target allocation`,
  app_periods: msg`which periods are available`,
  app_reference: msg`how something in the app works`,
  app_user_guide: msg`the guide for a screen`,
};

/** The values on the card, spelled out. Keys come from the tool's own `Params`. */
export const PARAM_LABELS: Record<string, MessageDescriptor> = {
  from: msg`from`,
  to: msg`to`,
  limit: msg`rows`,
  tree: msg`tree`,
  query: msg`search`,
  instrument: msg`instrument`,
  source: msg`provider`,
  symbol: msg`symbol`,
  note: msg`note`,
  price: msg`level`,
  direction: msg`direction`,
  period: msg`period`,
  topic: msg`topic`,
  screen: msg`screen`,
  list: msg`list`,
  node: msg`branch`,
  target: msg`target`,
  cash: msg`cash to invest`,
  months: msg`months ahead`,
  operation: msg`operation`,
  account: msg`account`,
  date: msg`date`,
  quantity: msg`quantity`,
  amount: msg`amount`,
  fees: msg`commission`,
  taxes: msg`tax`,
  currency: msg`currency`,
  occurrence: msg`occurrence`,
  instruments: msg`instruments`,
  share_percent: msg`share, %`,
  kind: msg`kind`,
  level: msg`level`,
  interval: msg`interval`,
  name: msg`name`,
  parent: msg`under`,
  excluded: msg`switched off`,
  weights: msg`weights`,
  group: msg`group`,
  accounts: msg`accounts`,
  plan: msg`plan`,
  buys: msg`buys`,
  every: msg`every`,
  start: msg`starts`,
  end: msg`ends`,
  active: msg`in use`,
  isin: msg`ISIN`,
  data_source: msg`provider`,
  data_symbol: msg`provider symbol`,
  mic: msg`venue`,
  settlement_account: msg`settles through`,
  opened_at: msg`opened`,
  with_transactions: msg`with its operations`,
  new_name: msg`new name`,
  new_date: msg`new date`,
  new_quantity: msg`new quantity`,
  new_price: msg`new price`,
  new_amount: msg`new amount`,
  new_fees: msg`new commission`,
  new_taxes: msg`new tax`,
  new_note: msg`new note`,
};

export function paramEntries(params: ToolParams): [string, string][] {
  return Object.entries(params);
}
