//! What the host answers the import wizard with, written down so the frontend's own test can be
//! driven by it. The file under `app/e2e/fixtures/` is generated from the real core over a real
//! broker export — a hand-written one would drift from the wire the day a field is renamed, and
//! then the wizard's test would pass against a shape the app never sends.
//!
//! Regenerate with `UPDATE_FIXTURES=1 cargo test -p sq-app --test wizard_fixture`, read the diff,
//! then run again without it.

use sq_app_lib::commands::import::ImportPreviewData;
use sq_core::import::{ImportOptions, ImportService, builtin_presets, parse_file};
use sq_core::model::Account;
use sq_core::storage::Store;
use std::path::{Path, PathBuf};

/// The sample the conformance fixture already owns: one export, one place.
fn sample() -> (PathBuf, Vec<u8>) {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../core/tests/fixtures/presets/trade-republic/export.csv");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    (path, bytes)
}

fn fixture_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../e2e/fixtures/import-wizard.json")
}

/// The wizard's whole conversation with the host: what it is answered before an account is
/// chosen, after one is, and what the commit returns.
fn conversation() -> serde_json::Value {
    let (_, bytes) = sample();
    let preset = builtin_presets()
        .iter()
        .find(|p| p.name == "Trade Republic")
        .expect("the shipped Trade Republic layout");

    // Ids written by hand: they reach the fixture through every draft, and a fresh uuid per run
    // would make the file differ from itself.
    let store = Store::open_in_memory().unwrap();
    let mut cash = Account::deposit("Trade Republic · cash", "EUR");
    cash.id = "fixture-cash".into();
    store.save_account(&cash).unwrap();
    let mut depot = Account::securities("Trade Republic", "EUR", &cash.id);
    depot.id = "fixture-depot".into();
    depot.reference_account_id = Some(cash.id.clone());
    store.save_account(&depot).unwrap();

    let service = ImportService::new(&store).with_base_currency("EUR");
    let headers = parse_file(&bytes, &preset.config).unwrap().headers;

    // Step 1 as the file arrives: recognised as a layout, with nowhere for the rows to land yet.
    let detected = service
        .preview(&bytes, &preset.config, Some(&preset.mapping()), &[])
        .unwrap();
    // Step 2 once the account is picked — the one answer the wizard cannot give itself.
    let mapping = preset.mapping().with_account(&depot.id);
    let mapped = service
        .preview(&bytes, &preset.config, Some(&mapping), &[])
        .unwrap();
    let result = service
        .commit(
            &mapped,
            &ImportOptions {
                new_security_source: Some("yahoo".into()),
                ..ImportOptions::default()
            },
        )
        .unwrap();

    let data = |preview, applied: Option<&str>| {
        serde_json::to_value(ImportPreviewData {
            preview,
            headers: headers.clone(),
            applied_template: applied.map(str::to_string),
            reader: None,
            reader_warnings: Vec::new(),
            skipped_readers: Vec::new(),
        })
        .unwrap()
    };

    serde_json::json!({
        "note": "Generated by app/src-tauri/tests/wizard_fixture.rs — do not edit by hand.",
        "file": "export.csv",
        "accounts": store.list_accounts().unwrap(),
        "detected": data(detected, Some("builtin:Trade Republic")),
        "mapped": data(mapped, None),
        "result": result,
    })
}

/// The frontend's fixture is the host's own answer, or the wizard's test proves nothing.
#[test]
fn the_wizard_fixture_is_what_the_host_would_answer() {
    let produced = serde_json::to_string_pretty(&conversation()).unwrap() + "\n";
    let path = fixture_path();
    if std::env::var_os("UPDATE_FIXTURES").is_some() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &produced).unwrap();
        panic!("fixture rewritten; read the diff, then run again without UPDATE_FIXTURES");
    }
    let stored = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "{}: {e} — run with UPDATE_FIXTURES=1 and read the diff",
            path.display()
        )
    });
    assert_eq!(
        serde_json::from_str::<serde_json::Value>(&stored).unwrap(),
        serde_json::from_str::<serde_json::Value>(&produced).unwrap(),
        "the host answers the wizard differently than the frontend's fixture says"
    );
}

/// The sample is worth using only because the wizard has something to do with it: an account to
/// pick, instruments to create, and a row or two to look at.
#[test]
fn the_sample_gives_the_wizard_something_to_ask() {
    let conversation = conversation();
    let mapped = &conversation["mapped"];
    let summary = &mapped["summary"];
    assert!(
        summary["unknown_securities"].as_u64().unwrap() > 0,
        "the sample creates no instrument, so the Instruments step has nothing to show"
    );
    assert!(
        summary["warnings"].as_u64().unwrap() > 0,
        "the sample raises no warning, so the review step has nothing to review"
    );
    assert_eq!(
        conversation["detected"]["mapping"]["account_id"],
        serde_json::Value::Null,
        "the file arrives with an account already chosen, so the wizard asks nothing"
    );
}
