import { lazy, Suspense, useState } from "react";
import { Trans, useLingui } from "@lingui/react/macro";
import { save } from "@tauri-apps/plugin-dialog";
import { FileTextIcon, PackageIcon } from "@phosphor-icons/react";
import { api } from "../../lib/api";
import { useUpdates } from "../../lib/updates";
import { COMPONENTS } from "../../generated/counts";
import { ErrorText, ListRow, Panel, Pending } from "../../components/ui";
import { HelpPanel } from "./HelpPanel";

// eslint-disable-next-line lingui/no-unlocalized-strings -- a URL, the same in every language.
const REPOSITORY = "https://github.com/vvvlladimir/stonqs";

/** Eight hundred rows are not a panel: they arrive when somebody asks to see them. */
const Dependencies = lazy(() => import("./Dependencies"));

/**
 * What the app is and what it does not promise, with the two ways into it above. The disclaimer
 * lives here rather than only in the README, because the README is not what anybody is looking at
 * while reading a return figure; the licence notices live here because MIT and BSD ask that they
 * travel with a compiled copy too.
 */
export function AboutPanel() {
  const { t } = useLingui();
  const updates = useUpdates();
  const [listing, setListing] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const saveNotices = async () => {
    setError(null);
    try {
      const path = await save({
        defaultPath: "THIRD-PARTY-NOTICES.md",
        filters: [{ name: "Markdown", extensions: ["md"] }],
      });
      if (!path) return;
      await api.noticesSave(path);
    } catch (e) {
      setError(e instanceof Error ? e : new Error(String(e)));
    }
  };

  return (
    <>
      <HelpPanel />

      <Panel
        title={t`About Stonqs`}
        info={t`What this app does with your figures, and what it does not promise about them.`}
        note={updates?.current ?? undefined}
      >
        <div className="prose">
          <p>
            <Trans>
              Stonqs is a tool for recording and analysing your own investments. It is not financial advice,
              and neither are the answers of the built-in assistant, which are generated by AI and can be
              wrong.
            </Trans>
          </p>
          <p>
            <Trans>
              Market data comes from free third-party sources with no guarantee of accuracy, completeness or
              availability. Check anything that matters against your broker's own statements — especially
              anything you intend to put on a tax return.
            </Trans>
          </p>
          <p className="dim">
            <Trans>
              Licensed under AGPL-3.0-only. You may run, study, change and share it; if you offer a modified
              version as a network service, that version's source must be available too.
            </Trans>{" "}
            <a href={REPOSITORY} target="_blank" rel="noreferrer noopener">
              {REPOSITORY}
            </a>
          </p>
        </div>
      </Panel>

      <Panel
        title={t`Third-party software`}
        info={t`Everything this app was built from, and the licence each part keeps.`}
      >
        <ListRow
          box
          lead={<PackageIcon />}
          title={t`Components`}
          sub={t`${COMPONENTS.rust} in the app and ${COMPONENTS.js} in the interface, each under its own licence.`}
          end={
            <button type="button" className="btn btn--sm" disabled={listing} onClick={() => setListing(true)}>
              <Trans>Show list</Trans>
            </button>
          }
        />
        <ListRow
          box
          lead={<FileTextIcon />}
          title={t`Licence notices`}
          sub={t`The full text each component asks to travel with a copy of the app.`}
          end={
            <button type="button" className="btn btn--sm" onClick={() => void saveNotices()}>
              <Trans>Save to a file…</Trans>
            </button>
          }
        />
        <ErrorText error={error} />
        {listing && (
          <Suspense fallback={<Pending />}>
            <Dependencies />
          </Suspense>
        )}
      </Panel>
    </>
  );
}
