/** One open conversation: history, the turn in flight, and the composer. */

import { useMemo, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Trans, useLingui } from "@lingui/react/macro";
import { api } from "../../../lib/api";
import { useChatSend } from "../../../lib/ai";
import {
  keys,
  useAiChats,
  useAiGrants,
  useAiMessages,
  useAiModels,
  useAiProviders,
  useInvalidate,
} from "../../../lib/queries";
import type { AiEffort, AiToolMode, UiError } from "../../../lib/types";
import { GrantedTools, Steps, ToolConsent } from "../AiTools";
import { EffortPicker, ModelPicker, ProviderPicker, ToolModeToggle, TokenCount } from "../AiControls";
import { liveSteps } from "../aiSteps";
import { ErrorText, QueryError, useUiErrorText } from "../../ui";
import { Composer } from "./Composer";
import { conversation } from "./conversation";
import { Opener, Said, Working } from "./Messages";
import { useScrollToEnd } from "./useScrollToEnd";

export function ActiveChat({ chatId }: { chatId: string }) {
  const { t } = useLingui();
  const invalidate = useInvalidate();
  const chats = useAiChats();
  const messages = useAiMessages(chatId);
  const grants = useAiGrants(chatId);
  const chat = chats.data?.find((entry) => entry.id === chatId);
  const mode: AiToolMode = chat?.tool_mode ?? "ASK";
  const providers = useAiProviders();
  // Keyed to the chat's own provider and only asked for once the chat is open: the list is a
  // network call, and the panel's list of chats should not pay for it.
  const models = useAiModels(chat?.provider ?? null, chat !== undefined);

  const setMode = useMutation({
    mutationFn: (next: AiToolMode) => api.aiChatSetMode(chatId, next),
    onSuccess: () => invalidate(keys.aiChats()),
  });
  const setEffort = useMutation({
    mutationFn: (next: AiEffort) => api.aiChatSetEffort(chatId, next),
    onSuccess: () => invalidate(keys.aiChats(), keys.settings()),
  });
  const setModel = useMutation({
    mutationFn: (next: string) => api.aiChatSetModel(chatId, next),
    onSuccess: () => invalidate(keys.aiChats(), keys.settings()),
  });
  const setProvider = useMutation({
    mutationFn: (next: string) => api.aiChatSetProvider(chatId, next),
    onSuccess: () => invalidate(keys.aiChats(), keys.settings()),
  });
  const { pending, thinking, busy, live, request, error, usage, send, decide, stop } = useChatSend(chatId);
  const [text, setText] = useState("");

  const stored = useMemo(() => conversation(messages.data ?? []), [messages.data]);
  const running = busy ? liveSteps(live, thinking, pending) : [];
  const empty = stored.length === 0 && !busy;

  const submit = (value: string) => {
    const asked = value.trim();
    if (!asked || busy) return;
    setText("");
    send(asked);
  };

  const scroller = useScrollToEnd([stored.length, running.length, pending, thinking, request]);

  return (
    <>
      <div className="ai-body" ref={scroller}>
        {messages.isError && <QueryError error={messages.error} />}
        {empty && <Opener onPick={submit} />}
        {stored.map((part) =>
          part.kind === "steps" ? (
            <Steps key={part.key} steps={part.steps} />
          ) : (
            <Said key={part.key} role={part.role} text={part.text} />
          ),
        )}
        {running.length > 0 && <Steps steps={running} />}
        {busy && pending && <Said role="model" text={pending} streaming />}
        {request && <ToolConsent request={request} onDecide={decide} />}
        {busy && !pending && running.length === 0 && !request && <Working />}
        {error && <TurnError error={error} />}
        {grants.data && grants.data.length > 0 && <GrantedTools tools={grants.data} />}
      </div>
      <div className="ai-compose">
        <TokenCount usage={usage} busy={busy} />
        <Composer
          text={text}
          busy={busy}
          placeholder={t`Ask about your portfolio…`}
          onChange={setText}
          onSubmit={() => submit(text)}
          onStop={stop}
        />
        <div className="ai-foot">
          <ToolModeToggle mode={mode} onChange={(next) => setMode.mutate(next)} />
          <EffortPicker effort={chat?.effort ?? "MEDIUM"} onChange={(next) => setEffort.mutate(next)} />
          {chat && (
            <ProviderPicker
              provider={chat.provider}
              providers={providers.data ?? []}
              onChange={(next) => setProvider.mutate(next)}
            />
          )}
          {chat && (
            <ModelPicker
              model={chat.model}
              models={models.data ?? []}
              loading={models.isPending}
              onChange={(next) => setModel.mutate(next)}
            />
          )}
        </div>
        <p className="ai-note">
          <Trans>
            Answers are generated by AI from your own data and can be wrong. Not investment advice.
          </Trans>
        </p>
      </div>
    </>
  );
}

/** A failed turn wears the app's one red line, from the host's code — never a raw message. */
function TurnError({ error }: { error: UiError }) {
  return <ErrorText>{useUiErrorText(error)}</ErrorText>;
}
