import { msg } from "@lingui/core/macro";
import {
  CalendarBlankIcon,
  ChartBarIcon,
  ChartLineDownIcon,
  ChartLineUpIcon,
  ChartPieSliceIcon,
  GridFourIcon,
  ScalesIcon,
  SquaresFourIcon,
} from "@phosphor-icons/react";
import { AllocationWidget, DriftWidget, TreemapWidget } from "../allocation";
import { BenchWidget, ChartWidget, ContributionWidget, DrawdownWidget, ReturnsWidget } from "../chart";
import { IncomeCalendarWidget, IncomeTaxonomyWidget } from "../income";
import type { WidgetDef } from "../model";

/** Widgets that draw a chart over the period or the portfolio's split. */
export const CHARTS: Record<string, WidgetDef> = {
  chart: {
    label: msg`Value and flows`,
    icon: ChartLineUpIcon,
    description: msg`The value line over the period with deposit bars beneath it.`,
    group: msg`Charts`,
    size: { w: 12, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "period"],
    Render: ChartWidget,
  },
  bench: {
    label: msg`Portfolio and benchmark`,
    icon: ChartBarIcon,
    description: msg`The growth of one invested unit against each chosen benchmark.`,
    group: msg`Charts`,
    size: { w: 6, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "period", "benchmark", "inflation"],
    Render: BenchWidget,
  },
  drawdown: {
    label: msg`Drawdown`,
    icon: ChartLineDownIcon,
    description: msg`How far the portfolio sits below its peak, by day.`,
    group: msg`Charts`,
    size: { w: 6, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "period"],
    Render: DrawdownWidget,
  },
  contribution: {
    label: msg`Who made the result`,
    icon: ChartBarIcon,
    description: msg`Each position's share of the return, largest first, with the total.`,
    group: msg`Charts`,
    size: { w: 6, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "period", "count"],
    defaults: { count: 8 },
    Render: ContributionWidget,
  },
  treemap: {
    label: msg`Share map`,
    icon: SquaresFourIcon,
    description: msg`Shares by area: the large and the small are visible at once.`,
    group: msg`Charts`,
    size: { w: 6, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "taxonomy"],
    Render: TreemapWidget,
  },
  returns: {
    label: msg`Return heatmap`,
    icon: GridFourIcon,
    description: msg`Monthly return by year: a bad season shows at a glance.`,
    group: msg`Charts`,
    size: { w: 6, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "period"],
    Render: ReturnsWidget,
  },
  incomecal: {
    label: msg`Income calendar`,
    icon: CalendarBlankIcon,
    description: msg`Dividends and interest by month and year: the seasonality shows.`,
    group: msg`Charts`,
    size: { w: 6, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "period"],
    Render: IncomeCalendarWidget,
  },
  incometax: {
    label: msg`Income by classification`,
    icon: ChartPieSliceIcon,
    description: msg`What each category of the tree paid over the period.`,
    group: msg`Charts`,
    size: { w: 6, h: 6 },
    min: { w: 3, h: 3 },
    fields: ["title", "source", "period", "taxonomy", "count"],
    defaults: { count: 8 },
    Render: IncomeTaxonomyWidget,
  },
  allocation: {
    label: msg`Composition`,
    icon: ChartPieSliceIcon,
    description: msg`Shares as one bar: by instrument or by classification.`,
    group: msg`Charts`,
    size: { w: 6, h: 6 },
    min: { w: 3, h: 3 },
    fields: ["title", "source", "taxonomy", "count"],
    defaults: { count: 8 },
    Render: AllocationWidget,
  },
  drift: {
    label: msg`Against the target`,
    icon: ScalesIcon,
    description: msg`Where each category stands against its target weight.`,
    group: msg`Charts`,
    size: { w: 6, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "target"],
    Render: DriftWidget,
  },
};
