import { msg } from "@lingui/core/macro";
import {
  ArrowsLeftRightIcon,
  BellRingingIcon,
  CalendarCheckIcon,
  CalendarDotsIcon,
  EyeIcon,
  ListBulletsIcon,
  NotepadIcon,
  TargetIcon,
  TrendUpIcon,
  WalletIcon,
  WaveSineIcon,
} from "@phosphor-icons/react";
import {
  CashWidget,
  ContributionsWidget,
  DatesWidget,
  EventsWidget,
  ExpectedDividendsWidget,
  LimitsWidget,
  PositionsWidget,
  WatchlistWidget,
} from "../list";
import { PerformersWidget, RiskWidget, TargetValueWidget, TradesWidget } from "../periodLists";
import type { WidgetDef } from "../model";

/** Widgets that list rows: what is due, what is held, what happened. */
export const LISTS: Record<string, WidgetDef> = {
  contributions: {
    label: msg`Upcoming contributions`,
    icon: CalendarDotsIcon,
    description: msg`What the plans pay in next, soonest first.`,
    group: msg`Lists`,
    size: { w: 4, h: 7 },
    min: { w: 3, h: 4 },
    fields: ["title", "count"],
    defaults: { count: 6 },
    Render: ContributionsWidget,
  },
  dividends: {
    label: msg`Expected dividends`,
    icon: CalendarCheckIcon,
    description: msg`What the positions should pay next, from each instrument's past year.`,
    group: msg`Lists`,
    size: { w: 4, h: 7 },
    min: { w: 3, h: 4 },
    fields: ["title", "source", "count"],
    defaults: { count: 6 },
    Render: ExpectedDividendsWidget,
  },
  watchlist: {
    label: msg`Watchlist`,
    icon: EyeIcon,
    description: msg`Instruments you follow: the last price and the period's move.`,
    group: msg`Lists`,
    size: { w: 4, h: 7 },
    min: { w: 3, h: 4 },
    fields: ["title", "watchlist", "period", "count"],
    defaults: { count: 6 },
    Render: WatchlistWidget,
  },
  limits: {
    label: msg`Level crossings`,
    icon: BellRingingIcon,
    description: msg`The latest closes that crossed a level you set, either way.`,
    group: msg`Lists`,
    size: { w: 4, h: 7 },
    min: { w: 3, h: 4 },
    fields: ["title", "count"],
    defaults: { count: 6 },
    Render: LimitsWidget,
  },
  dates: {
    label: msg`Dates reached`,
    icon: CalendarCheckIcon,
    description: msg`Instruments whose review date has arrived.`,
    group: msg`Lists`,
    size: { w: 4, h: 7 },
    min: { w: 3, h: 4 },
    fields: ["title", "count"],
    defaults: { count: 6 },
    Render: DatesWidget,
  },
  events: {
    label: msg`Instrument events`,
    icon: NotepadIcon,
    description: msg`Notes, dividends and splits, newest first.`,
    group: msg`Lists`,
    size: { w: 4, h: 7 },
    min: { w: 3, h: 4 },
    fields: ["title", "count"],
    defaults: { count: 6 },
    Render: EventsWidget,
  },
  targetvalue: {
    label: msg`Target value`,
    icon: TargetIcon,
    description: msg`What each category should be worth, and how far off it is.`,
    group: msg`Lists`,
    size: { w: 6, h: 9 },
    min: { w: 3, h: 6 },
    fields: ["title", "source", "target", "count"],
    defaults: { count: 6 },
    Render: TargetValueWidget,
  },
  positions: {
    label: msg`Largest positions`,
    icon: ListBulletsIcon,
    description: msg`The top of the positions table: weight, value, today.`,
    group: msg`Lists`,
    size: { w: 6, h: 9 },
    min: { w: 3, h: 6 },
    fields: ["title", "source", "count"],
    defaults: { count: 6 },
    Render: PositionsWidget,
  },
  performers: {
    label: msg`Top performers`,
    icon: TrendUpIcon,
    description: msg`The best return of the period, whatever the position is worth.`,
    group: msg`Lists`,
    size: { w: 6, h: 9 },
    min: { w: 3, h: 6 },
    fields: ["title", "source", "period", "count"],
    defaults: { count: 6 },
    Render: PerformersWidget,
  },
  cash: {
    label: msg`Cash accounts`,
    icon: WalletIcon,
    description: msg`Account balances, each in its own currency.`,
    group: msg`Lists`,
    size: { w: 3, h: 6 },
    min: { w: 3, h: 3 },
    fields: ["title", "source"],
    Render: CashWidget,
  },
  trades: {
    label: msg`Closed trades`,
    icon: ArrowsLeftRightIcon,
    description: msg`The trades the period closed, largest result first.`,
    group: msg`Lists`,
    size: { w: 6, h: 9 },
    min: { w: 3, h: 6 },
    fields: ["title", "source", "period", "count"],
    defaults: { count: 6 },
    Render: TradesWidget,
  },
  risk: {
    label: msg`Risk`,
    icon: WaveSineIcon,
    description: msg`Volatility, Sharpe and the maximum drawdown over the period.`,
    group: msg`Lists`,
    size: { w: 3, h: 6 },
    min: { w: 3, h: 6 },
    fields: ["title", "source", "period"],
    Render: RiskWidget,
  },
};
