//! What a header may be called, per field.
//!
//! Detection is per *language*, never per broker: a rule keyed to one broker's file helps only
//! that broker's customers. Each list is ordered **canonical-first**, because the index breaks
//! ties inside a match tier — reordering one of these changes which column wins.

use super::ImportField;

impl ImportField {
    pub(crate) fn header_aliases(self) -> &'static [&'static str] {
        match self {
            // Aliases are ordered canonical-first: the index breaks ties inside a tier.
            // Languages, not brokers: a rule tied to one broker's file helps nobody else.
            ImportField::Date => &[
                "date",
                "datum",
                "tradedate",
                "transactiondate",
                "valuedate",
                "settledate",
                "settlementdate",
                "activitydate",
                "bookingdate",
                "datetime",
                "timestamp",
                "time",
                "executedat",
                "buchungstag",
                "handelstag",
                "data",
                "fecha",
                "дата",
            ],
            ImportField::Kind => &[
                "type",
                "transactiontype",
                "activitytype",
                "action",
                "side",
                "buysell",
                "way",
                "operation",
                "event",
                "transaction",
                "kind",
                "category",
                "typ",
                "tipo",
                "soort",
                "art",
                "transaktionstyp",
                "kategorie",
                "categorie",
                "categoria",
                "вид",
                "тип",
                "операция",
            ],
            ImportField::Symbol => &[
                "symbol",
                "ticker",
                "tickersymbol",
                "securitysymbol",
                "instrumentsymbol",
                "stocksymbol",
                "assetid",
                "wkn",
                "cusip",
                "sedol",
                "instrument",
                "security",
                "asset",
                "stock",
                "тикер",
            ],
            ImportField::Isin => &["isin", "isincode"],

            ImportField::Name => &[
                "name",
                "securityname",
                "instrumentname",
                "assetname",
                "holdingname",
                "wertpapier",
                "bezeichnung",
                "produkt",
                "product",
                "naam",
                "nome",
                "nombre",
                "denominazione",
                "beskrivning",
                "наименование",
                "название",
            ],
            ImportField::Quantity => &[
                "quantity",
                "qty",
                "shares",
                "units",
                "numberofshares",
                "noofshares",
                "numshares",
                "volume",
                "stück",
                "stuck",
                "anzahl",
                "aantal",
                "antal",
                "quantità",
                "quantita",
                "quantité",
                "quantite",
                "cantidad",
                "ilość",
                "ilosc",
                "количество",
            ],
            ImportField::Price => &[
                "price",
                "unitprice",
                "priceperunit",
                "pricepershare",
                "shareprice",
                "tradeprice",
                "executionprice",
                "kurs",
                "koers",
                "preis",
                "prezzo",
                "precio",
                "prix",
                "cena",
                "цена",
            ],
            ImportField::Amount => &[
                "amount",
                "totalamount",
                "netamount",
                "grossamount",
                "transactionamount",
                "cashflow",
                "total",
                "value",
                "proceeds",
                "betrag",
                "bedrag",
                "belopp",
                "waarde",
                "importo",
                "importe",
                "montant",
                "monto",
                "kwota",
                "gesamt",
                "сумма",
            ],
            ImportField::Fee => &[
                "fee",
                "fees",
                "feescomm",
                "commission",
                "commissions",
                "brokerage",
                "charges",
                "costs",
                "gebühr",
                "gebuehr",
                "kosten",
                "courtage",
                "provision",
                "frais",
                "comision",
                "comisión",
                "commissioni",
                "prowizja",
                "комиссия",
            ],
            ImportField::Tax => &[
                "tax",
                "taxes",
                "withholdingtax",
                "withholding",
                "stampduty",
                "sdrt",
                "levy",
                "steuer",
                "belasting",
                "imposta",
                "impuesto",
                "impot",
                "impôt",
                "podatek",
                "налог",
            ],
            ImportField::Currency => &[
                "currency",
                "currencycode",
                "transactioncurrency",
                "ccy",
                "curr",
                "währung",
                "wahrung",
                "valuta",
                "divisa",
                "devise",
                "moneda",
                "waluta",
                "валюта",
            ],
            ImportField::FeeCurrency => &[
                "feecurrency",
                "feecurrencycode",
                "commissioncurrency",
                "feeccy",
                "commissionccy",
                "gebührenwährung",
                "валютакомиссии",
            ],
            ImportField::TaxCurrency => &[
                "taxcurrency",
                "taxcurrencycode",
                "withholdingtaxcurrency",
                "taxccy",
                "steuerwährung",
                "валютаналога",
            ],
            ImportField::FxRate => &[
                "fxrate",
                "exchangerate",
                "conversionrate",
                "currencyrate",
                "valutakurs",
                "wechselkurs",
                "tassocambio",
                "tipocambio",
                "rate",
                "курс",
            ],
            ImportField::Account => &[
                "account",
                "accountid",
                "accountname",
                "accountnumber",
                "acct",
                "konto",
                "depot",
                "portfolio",
                "portefeuille",
                "rekening",
                "conto",
                "cuenta",
                "compte",
                "счёт",
                "счет",
            ],
            ImportField::LinkId => &[
                "linkid",
                "transferid",
                "referenceid",
                "reference",
                "orderid",
                "ordernumber",
                "tradeid",
                "transactionid",
                "связка",
            ],
            ImportField::ExternalId => &[
                "externalid",
                "transactionid",
                "orderid",
                "tradeid",
                "bookingid",
                "referenceid",
                "operationid",
                "идентификатороперации",
            ],
            ImportField::Note => &[
                "note",
                "notes",
                "comment",
                "comments",
                "description",
                "memo",
                "remarks",
                "details",
                "narrative",
                "kommentar",
                "bemerkung",
                "omschrijving",
                "opmerking",
                "descrizione",
                "descripcion",
                "примечание",
            ],
        }
    }
}
