//! What an operation may be called, per transaction kind.
//!
//! Ordered canonical-first like the header aliases, and sell wordings precede buy ones because
//! one contains the other ("Verkoop" contains "Koop").

use super::normalize_alias;
use crate::model::TransactionKind;
use std::collections::BTreeMap;

pub fn default_kind_aliases() -> BTreeMap<String, TransactionKind> {
    use TransactionKind::*;
    let table: &[(&str, TransactionKind)] = &[
        ("BUY", Buy),
        ("PURCHASE", Buy),
        ("KAUF", Buy),
        ("KAUFEN", Buy),
        ("ПОКУПКА", Buy),
        ("SELL", Sell),
        ("SALE", Sell),
        ("VERKAUF", Sell),
        ("ПРОДАЖА", Sell),
        ("DIVIDEND", Dividend),
        ("DIVIDENDE", Dividend),
        ("DIV", Dividend),
        ("DISTRIBUTION", Dividend),
        ("ДИВИДЕНДЫ", Dividend),
        ("INTEREST", Interest),
        ("ZINSEN", Interest),
        ("COUPON", Interest),
        ("КУПОН", Interest),
        ("ПРОЦЕНТЫ", Interest),
        ("INTERESTCHARGE", InterestCharge),
        ("SOLLZINSEN", InterestCharge),
        ("FEE", Fee),
        ("COMMISSION", Fee),
        ("GEBÜHR", Fee),
        ("GEBUEHR", Fee),
        ("КОМИССИЯ", Fee),
        ("FEEREFUND", FeeRefund),
        ("GEBÜHRENERSTATTUNG", FeeRefund),
        ("TAX", Tax),
        ("WITHHOLDING", Tax),
        ("STEUER", Tax),
        ("НАЛОГ", Tax),
        ("TAXREFUND", TaxRefund),
        ("STEUERERSTATTUNG", TaxRefund),
        ("DEPOSIT", Deposit),
        ("CONTRIBUTION", Deposit),
        ("EINZAHLUNG", Deposit),
        ("ПОПОЛНЕНИЕ", Deposit),
        ("WITHDRAWAL", Withdrawal),
        ("AUSZAHLUNG", Withdrawal),
        ("ВЫВОД", Withdrawal),
        ("TRANSFERIN", TransferIn),
        ("TRANSFEROUT", TransferOut),
        ("TRANSFERINBOUND", TransferIn),
        ("TRANSFERINSTANTINBOUND", TransferIn),
        ("TRANSFEROUTBOUND", TransferOut),
        ("TRANSFERINSTANTOUTBOUND", TransferOut),
        ("INTERESTPAYMENT", Interest),
        ("DIVIDENDPAYMENT", Dividend),
        ("DELIVERYINBOUND", DeliveryInbound),
        ("EINLIEFERUNG", DeliveryInbound),
        ("DELIVERYOUTBOUND", DeliveryOutbound),
        ("AUSLIEFERUNG", DeliveryOutbound),
        ("SECURITYTRANSFERIN", SecurityTransferIn),
        ("SECURITYTRANSFEROUT", SecurityTransferOut),
    ];
    table.iter().map(|(k, v)| (normalize_alias(k), *v)).collect()
}

/// Operation wording recognised by keyword: "Stocks/ETF purchase", "Market buy" and
/// "Aankoop" all say Buy. The table is per language, never per broker — a rule for one
/// broker's file helps only that broker's customers. Order matters: the first hit wins, so
/// "Withdrawal Conversion Fee" is a fee and "Verkoop" is not the "Koop" it contains.
pub(crate) fn kind_from_keywords(normalized: &str) -> Option<TransactionKind> {
    use TransactionKind::*;
    const KEYWORDS: &[(&str, TransactionKind)] = &[
        ("WITHHOLDING", Tax),
        ("STAMPDUTY", Tax),
        ("SDRT", Tax),
        ("TAX", Tax),
        ("STEUER", Tax),
        ("BELASTING", Tax),
        ("IMPOSTA", Tax),
        ("IMPUESTO", Tax),
        ("PODATEK", Tax),
        ("KÄLLSKATT", Tax),
        ("RITENUTA", Tax),
        ("НАЛОГ", Tax),
        ("FEE", Fee),
        ("COMMISSION", Fee),
        ("COURTAGE", Fee),
        ("GEBÜHR", Fee),
        ("GEBUEHR", Fee),
        ("KOSTEN", Fee),
        ("PROVISION", Fee),
        ("FRAIS", Fee),
        ("CHARGE", Fee),
        ("PROWIZJA", Fee),
        ("TARIEVEN", Fee),
        ("КОМИССИЯ", Fee),
        ("CASHBACK", Cashback),
        ("REBATE", Cashback),
        ("REFERRAL", Cashback),
        ("КЕШБЭК", Cashback),
        ("КЭШБЭК", Cashback),
        ("REWARD", Reward),
        ("STAKINGINCOME", Reward),
        ("AIRDROP", Reward),
        ("НАГРАД", Reward),
        ("ВОЗНАГРАЖД", Reward),
        ("INTEREST", Interest),
        ("INTERESSI", Interest),
        ("RÄNTA", Interest),
        ("COUPON", Interest),
        ("CEDOLA", Interest),
        ("INTÉR", Interest),
        ("ZINSEN", Interest),
        ("RENTE", Interest),
        ("ПРОЦЕНТ", Interest),
        ("DIVIDEND", Dividend),
        ("DIVIDENDO", Dividend),
        ("UTDELNING", Dividend),
        ("PROVENTO", Dividend),
        ("ДИВИДЕНД", Dividend),
        ("VERKAUF", Sell),
        ("VERKOOP", Sell),
        ("SELL", Sell),
        ("SALE", Sell),
        ("VEND", Sell),
        ("VENTE", Sell),
        ("SPRZEDA", Sell),
        ("SÄLJ", Sell),
        ("ПРОДАЖА", Sell),
        ("AANKOOP", Buy),
        ("KOOP", Buy),
        ("BUY", Buy),
        ("PURCHASE", Buy),
        ("KAUF", Buy),
        ("ACHAT", Buy),
        ("COMPRA", Buy),
        ("ACQUIST", Buy),
        ("ZAKUP", Buy),
        ("KÖP", Buy),
        ("ПОКУПКА", Buy),
        ("WITHDRAW", Withdrawal),
        ("AUSZAHLUNG", Withdrawal),
        ("ONTTREKKING", Withdrawal),
        ("OPNAME", Withdrawal),
        ("UTTAG", Withdrawal),
        ("RETIRADA", Withdrawal),
        ("RETRAIT", Withdrawal),
        ("PRELIEVO", Withdrawal),
        ("WYPLATA", Withdrawal),
        ("СНЯТИЕ", Withdrawal),
        ("DEPOSIT", Deposit),
        ("TOPUP", Deposit),
        ("EINZAHLUNG", Deposit),
        ("STORTING", Deposit),
        ("INSÄTTNING", Deposit),
        ("VERSEMENT", Deposit),
        ("INGRESO", Deposit),
        ("WPLATA", Deposit),
        ("COTISATION", Deposit),
        ("SUBVENTION", Deposit),
        ("ПОПОЛНЕНИЕ", Deposit),
        // Moving value inside the portfolio: a currency exchange, a crypto conversion, a
        // stake, a wallet-to-wallet move. Direction comes from the amount's sign, so one
        // keyword covers both legs — `TransferIn` is the reversible side of the pair.
        (">", TransferIn),
        ("CONVERSION", TransferIn),
        ("CONVERT", TransferIn),
        ("КОНВЕРТ", TransferIn),
        ("EXCHANGE", TransferIn),
        ("FOREX", TransferIn),
        ("SWAP", TransferIn),
        ("STAK", TransferIn),
        ("RECEIVE", TransferIn),
        ("SEND", TransferOut),
        ("LOCKUP", TransferIn),
        ("TRANSFER", TransferIn),
        ("ÜBERTRAG", TransferIn),
        ("UEBERTRAG", TransferIn),
        ("OVERBOEKING", TransferIn),
        ("TRASFERIMENTO", TransferIn),
        ("TRANSFERENCIA", TransferIn),
        ("ПЕРЕВОД", TransferIn),
    ];
    KEYWORDS
        .iter()
        .find(|(word, _)| normalized.contains(word))
        .map(|(_, kind)| *kind)
}
