import { msg } from "@lingui/core/macro";
import {
  BellRingingIcon,
  CalendarBlankIcon,
  CalendarCheckIcon,
  CalendarDotsIcon,
  EyeIcon,
  NotepadIcon,
  ChartBarIcon,
  ChartLineDownIcon,
  ChartLineUpIcon,
  ChartPieSliceIcon,
  DivideIcon,
  FlagCheckeredIcon,
  ArrowsLeftRightIcon,
  ScalesIcon,
  TargetIcon,
  GaugeIcon,
  GridFourIcon,
  ListBulletsIcon,
  SparkleIcon,
  SquaresFourIcon,
  TextHOneIcon,
  TrendUpIcon,
  WalletIcon,
  WaveSineIcon,
} from "@phosphor-icons/react";
import { BriefWidget } from "./ai";
import { METRICS } from "./metrics";
import { HeadingWidget, MetricWidget } from "./tiles";
import { FireWidget, RatioWidget } from "./value";
import { RATIO_TERMS, ratioTerms } from "./model";
import {
  AllocationWidget,
  BenchWidget,
  ChartWidget,
  ContributionWidget,
  DrawdownWidget,
  DriftWidget,
  IncomeCalendarWidget,
  IncomeTaxonomyWidget,
  ReturnsWidget,
  TreemapWidget,
} from "./chart";
import {
  CashWidget,
  ContributionsWidget,
  ExpectedDividendsWidget,
  DatesWidget,
  EventsWidget,
  LimitsWidget,
  PerformersWidget,
  PositionsWidget,
  RiskWidget,
  TargetValueWidget,
  TradesWidget,
  WatchlistWidget,
} from "./list";
import type { WidgetDef } from "./model";
import type { Widget } from "../../../lib/uiState";

export { periodOf, widgetMeta, widgetTitle } from "./model";
export type { Field, WidgetDef, WidgetProps } from "./model";

/** The dashboard catalog: one entry per widget the user can place, grouped for the picker. */
export const WIDGETS: Record<string, WidgetDef> = {
  contributions: {
    label: msg`Upcoming contributions`,
    icon: CalendarDotsIcon,
    description: msg`What the plans pay in next, soonest first.`,
    group: msg`Lists`,
    size: { w: 4, h: 7 },
    min: { w: 3, h: 4 },
    fields: ["title", "count"],
    defaults: { count: 6 },
    Render: ContributionsWidget,
  },
  dividends: {
    label: msg`Expected dividends`,
    icon: CalendarCheckIcon,
    description: msg`What the positions should pay next, from each instrument's past year.`,
    group: msg`Lists`,
    size: { w: 4, h: 7 },
    min: { w: 3, h: 4 },
    fields: ["title", "source", "count"],
    defaults: { count: 6 },
    Render: ExpectedDividendsWidget,
  },
  watchlist: {
    label: msg`Watchlist`,
    icon: EyeIcon,
    description: msg`Instruments you follow: the last price and the period's move.`,
    group: msg`Lists`,
    size: { w: 4, h: 7 },
    min: { w: 3, h: 4 },
    fields: ["title", "watchlist", "period", "count"],
    defaults: { count: 6 },
    Render: WatchlistWidget,
  },
  limits: {
    label: msg`Level crossings`,
    icon: BellRingingIcon,
    description: msg`The latest closes that crossed a level you set, either way.`,
    group: msg`Lists`,
    size: { w: 4, h: 7 },
    min: { w: 3, h: 4 },
    fields: ["title", "count"],
    defaults: { count: 6 },
    Render: LimitsWidget,
  },
  dates: {
    label: msg`Dates reached`,
    icon: CalendarCheckIcon,
    description: msg`Instruments whose review date has arrived.`,
    group: msg`Lists`,
    size: { w: 4, h: 7 },
    min: { w: 3, h: 4 },
    fields: ["title", "count"],
    defaults: { count: 6 },
    Render: DatesWidget,
  },
  events: {
    label: msg`Instrument events`,
    icon: NotepadIcon,
    description: msg`Notes, dividends and splits, newest first.`,
    group: msg`Lists`,
    size: { w: 4, h: 7 },
    min: { w: 3, h: 4 },
    fields: ["title", "count"],
    defaults: { count: 6 },
    Render: EventsWidget,
  },
  metric: {
    label: msg`Metric`,
    icon: GaugeIcon,
    description: msg`One number from the catalog: value, return, drawdown.`,
    group: msg`Numbers`,
    size: { w: 3, h: 3 },
    min: { w: 2, h: 3 },
    fields: ["title", "source", "metric", "period", "foot"],
    defaults: { metric: "value" },
    titleOf: (i18n, cfg) => {
      const metric = METRICS[String(cfg.metric)];
      return metric ? i18n._(metric.label) : i18n._(msg`Metric`);
    },
    periodicFor: (cfg) => METRICS[String(cfg.metric)]?.periodic === true,
    Render: MetricWidget,
  },
  ratio: {
    label: msg`Ratio`,
    icon: DivideIcon,
    description: msg`One figure over another: a yield, a cost share, how much of it is cash.`,
    group: msg`Numbers`,
    size: { w: 3, h: 3 },
    min: { w: 2, h: 3 },
    fields: ["title", "source", "ratio", "period", "foot"],
    defaults: { top: "income", bottom: "value" },
    titleOf: (i18n, cfg) => {
      const { top, bottom } = ratioTerms(cfg);
      return `${i18n._(RATIO_TERMS[top].label)} / ${i18n._(RATIO_TERMS[bottom].label)}`;
    },
    periodicFor: (cfg) => {
      const { top, bottom } = ratioTerms(cfg);
      return RATIO_TERMS[top].periodic === true || RATIO_TERMS[bottom].periodic === true;
    },
    Render: RatioWidget,
  },
  fire: {
    label: msg`Financial independence`,
    icon: FlagCheckeredIcon,
    description: msg`How far the portfolio is from covering a year of spending, and when this pace gets there.`,
    group: msg`Numbers`,
    size: { w: 4, h: 4 },
    min: { w: 3, h: 3 },
    fields: ["title", "fire"],
    defaults: { withdrawal: "0.04", return: "0.05" },
    Render: FireWidget,
  },
  chart: {
    label: msg`Value and flows`,
    icon: ChartLineUpIcon,
    description: msg`The value line over the period with deposit bars beneath it.`,
    group: msg`Charts`,
    size: { w: 12, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "period"],
    Render: ChartWidget,
  },
  bench: {
    label: msg`Portfolio and benchmark`,
    icon: ChartBarIcon,
    description: msg`The growth of one invested unit against each chosen benchmark.`,
    group: msg`Charts`,
    size: { w: 6, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "period", "benchmark", "inflation"],
    Render: BenchWidget,
  },
  drawdown: {
    label: msg`Drawdown`,
    icon: ChartLineDownIcon,
    description: msg`How far the portfolio sits below its peak, by day.`,
    group: msg`Charts`,
    size: { w: 6, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "period"],
    Render: DrawdownWidget,
  },
  contribution: {
    label: msg`Who made the result`,
    icon: ChartBarIcon,
    description: msg`Each position's share of the return, largest first, with the total.`,
    group: msg`Charts`,
    size: { w: 6, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "period", "count"],
    defaults: { count: 8 },
    Render: ContributionWidget,
  },
  treemap: {
    label: msg`Share map`,
    icon: SquaresFourIcon,
    description: msg`Shares by area: the large and the small are visible at once.`,
    group: msg`Charts`,
    size: { w: 6, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "taxonomy"],
    Render: TreemapWidget,
  },
  returns: {
    label: msg`Return heatmap`,
    icon: GridFourIcon,
    description: msg`Monthly return by year: a bad season shows at a glance.`,
    group: msg`Charts`,
    size: { w: 6, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "period"],
    Render: ReturnsWidget,
  },
  incomecal: {
    label: msg`Income calendar`,
    icon: CalendarBlankIcon,
    description: msg`Dividends and interest by month and year: the seasonality shows.`,
    group: msg`Charts`,
    size: { w: 6, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "period"],
    Render: IncomeCalendarWidget,
  },
  incometax: {
    label: msg`Income by classification`,
    icon: ChartPieSliceIcon,
    description: msg`What each category of the tree paid over the period.`,
    group: msg`Charts`,
    size: { w: 6, h: 6 },
    min: { w: 3, h: 3 },
    fields: ["title", "source", "period", "taxonomy", "count"],
    defaults: { count: 8 },
    Render: IncomeTaxonomyWidget,
  },
  allocation: {
    label: msg`Composition`,
    icon: ChartPieSliceIcon,
    description: msg`Shares as one bar: by instrument or by classification.`,
    group: msg`Charts`,
    size: { w: 6, h: 6 },
    min: { w: 3, h: 3 },
    fields: ["title", "source", "taxonomy", "count"],
    defaults: { count: 8 },
    Render: AllocationWidget,
  },
  drift: {
    label: msg`Against the target`,
    icon: ScalesIcon,
    description: msg`Where each category stands against its target weight.`,
    group: msg`Charts`,
    size: { w: 6, h: 9 },
    min: { w: 4, h: 6 },
    fields: ["title", "source", "target"],
    Render: DriftWidget,
  },
  targetvalue: {
    label: msg`Target value`,
    icon: TargetIcon,
    description: msg`What each category should be worth, and how far off it is.`,
    group: msg`Lists`,
    size: { w: 6, h: 9 },
    min: { w: 3, h: 6 },
    fields: ["title", "source", "target", "count"],
    defaults: { count: 6 },
    Render: TargetValueWidget,
  },
  positions: {
    label: msg`Largest positions`,
    icon: ListBulletsIcon,
    description: msg`The top of the positions table: weight, value, today.`,
    group: msg`Lists`,
    size: { w: 6, h: 9 },
    min: { w: 3, h: 6 },
    fields: ["title", "source", "count"],
    defaults: { count: 6 },
    Render: PositionsWidget,
  },
  performers: {
    label: msg`Top performers`,
    icon: TrendUpIcon,
    description: msg`The best return of the period, whatever the position is worth.`,
    group: msg`Lists`,
    size: { w: 6, h: 9 },
    min: { w: 3, h: 6 },
    fields: ["title", "source", "period", "count"],
    defaults: { count: 6 },
    Render: PerformersWidget,
  },
  cash: {
    label: msg`Cash accounts`,
    icon: WalletIcon,
    description: msg`Account balances, each in its own currency.`,
    group: msg`Lists`,
    size: { w: 3, h: 6 },
    min: { w: 3, h: 3 },
    fields: ["title", "source"],
    Render: CashWidget,
  },
  trades: {
    label: msg`Closed trades`,
    icon: ArrowsLeftRightIcon,
    description: msg`The trades the period closed, largest result first.`,
    group: msg`Lists`,
    size: { w: 6, h: 9 },
    min: { w: 3, h: 6 },
    fields: ["title", "source", "period", "count"],
    defaults: { count: 6 },
    Render: TradesWidget,
  },
  risk: {
    label: msg`Risk`,
    icon: WaveSineIcon,
    description: msg`Volatility, Sharpe and the maximum drawdown over the period.`,
    group: msg`Lists`,
    size: { w: 3, h: 6 },
    min: { w: 3, h: 6 },
    fields: ["title", "source", "period"],
    Render: RiskWidget,
  },
  brief: {
    label: msg`Portfolio summary`,
    icon: SparkleIcon,
    description: msg`What the period did and what drove it, written by the assistant on request.`,
    group: msg`Text`,
    size: { w: 6, h: 6 },
    min: { w: 3, h: 4 },
    fields: ["title", "source", "period", "prompt", "length", "refresh", "model"],
    Render: BriefWidget,
  },
  heading: {
    label: msg`Section heading`,
    icon: TextHOneIcon,
    description: msg`A divider line: it splits the dashboard into meaningful parts.`,
    group: msg`Text`,
    size: { w: 12, h: 2 },
    min: { w: 12, h: 2 },
    fields: ["title"],
    plain: true,
    Render: HeadingWidget,
  },
};

/** Create a catalog widget at the size the catalog says it reads best. */
export function makeWidget(type: string, id: string): Widget {
  const def = WIDGETS[type];
  return { id, type, w: def.size.w, h: def.size.h, cfg: { ...(def.defaults ?? {}) } };
}
