//! Consumer-price index regions as each source names them.
//!
//! The app's own code for a region is ISO 3166-1 alpha-2, which is what a locale carries, plus
//! the two aggregates Eurostat publishes (`EA`, `EU`). A source that speaks another vocabulary
//! translates here and nowhere else.

/// Eurostat writes Greece `EL` and the United Kingdom `UK`, against the standard it otherwise
/// follows. Kosovo has no alpha-2 code at all and is `XK` by convention, which Eurostat shares.
pub(crate) fn eurostat_geo(region: &str) -> String {
    match region {
        "GR" => "EL".into(),
        "GB" => "UK".into(),
        other => other.into(),
    }
}

/// The IMF speaks alpha-3, and two of its economies are not countries: Kosovo and the West Bank
/// and Gaza. Everything this table does not name, that source cannot answer.
pub(crate) fn imf_country(region: &str) -> Option<&'static str> {
    match region {
        "XK" => Some("KOS"),
        "PS" => Some("WBG"),
        other => ALPHA3.iter().find_map(|(a2, a3)| (*a2 == other).then_some(*a3)),
    }
}

/// Every region the IMF answers for, in this app's vocabulary.
pub(crate) fn alpha2() -> impl Iterator<Item = &'static str> {
    ALPHA3.iter().map(|(a2, _)| *a2).chain(["XK", "PS"])
}

/// Alpha-2 to alpha-3, cut to the economies the IMF actually publishes a CPI for.
const ALPHA3: &[(&str, &str)] = &[
    ("AE", "ARE"),
    ("AF", "AFG"),
    ("AG", "ATG"),
    ("AL", "ALB"),
    ("AM", "ARM"),
    ("AO", "AGO"),
    ("AR", "ARG"),
    ("AT", "AUT"),
    ("AU", "AUS"),
    ("AW", "ABW"),
    ("AZ", "AZE"),
    ("BA", "BIH"),
    ("BB", "BRB"),
    ("BD", "BGD"),
    ("BE", "BEL"),
    ("BF", "BFA"),
    ("BG", "BGR"),
    ("BH", "BHR"),
    ("BI", "BDI"),
    ("BJ", "BEN"),
    ("BN", "BRN"),
    ("BO", "BOL"),
    ("BR", "BRA"),
    ("BS", "BHS"),
    ("BT", "BTN"),
    ("BW", "BWA"),
    ("BY", "BLR"),
    ("BZ", "BLZ"),
    ("CA", "CAN"),
    ("CD", "COD"),
    ("CF", "CAF"),
    ("CG", "COG"),
    ("CH", "CHE"),
    ("CI", "CIV"),
    ("CL", "CHL"),
    ("CM", "CMR"),
    ("CN", "CHN"),
    ("CO", "COL"),
    ("CR", "CRI"),
    ("CV", "CPV"),
    ("CW", "CUW"),
    ("CY", "CYP"),
    ("CZ", "CZE"),
    ("DE", "DEU"),
    ("DJ", "DJI"),
    ("DK", "DNK"),
    ("DM", "DMA"),
    ("DO", "DOM"),
    ("DZ", "DZA"),
    ("EC", "ECU"),
    ("EE", "EST"),
    ("EG", "EGY"),
    ("ES", "ESP"),
    ("ET", "ETH"),
    ("FI", "FIN"),
    ("FJ", "FJI"),
    ("FR", "FRA"),
    ("GA", "GAB"),
    ("GB", "GBR"),
    ("GD", "GRD"),
    ("GE", "GEO"),
    ("GH", "GHA"),
    ("GM", "GMB"),
    ("GN", "GIN"),
    ("GP", "GLP"),
    ("GQ", "GNQ"),
    ("GR", "GRC"),
    ("GT", "GTM"),
    ("GW", "GNB"),
    ("GY", "GUY"),
    ("HK", "HKG"),
    ("HN", "HND"),
    ("HR", "HRV"),
    ("HT", "HTI"),
    ("HU", "HUN"),
    ("ID", "IDN"),
    ("IE", "IRL"),
    ("IL", "ISR"),
    ("IN", "IND"),
    ("IQ", "IRQ"),
    ("IR", "IRN"),
    ("IS", "ISL"),
    ("IT", "ITA"),
    ("JM", "JAM"),
    ("JO", "JOR"),
    ("JP", "JPN"),
    ("KE", "KEN"),
    ("KG", "KGZ"),
    ("KH", "KHM"),
    ("KI", "KIR"),
    ("KM", "COM"),
    ("KN", "KNA"),
    ("KR", "KOR"),
    ("KW", "KWT"),
    ("KZ", "KAZ"),
    ("LA", "LAO"),
    ("LB", "LBN"),
    ("LC", "LCA"),
    ("LK", "LKA"),
    ("LR", "LBR"),
    ("LS", "LSO"),
    ("LT", "LTU"),
    ("LU", "LUX"),
    ("LV", "LVA"),
    ("LY", "LBY"),
    ("MA", "MAR"),
    ("MD", "MDA"),
    ("ME", "MNE"),
    ("MG", "MDG"),
    ("MK", "MKD"),
    ("ML", "MLI"),
    ("MM", "MMR"),
    ("MN", "MNG"),
    ("MO", "MAC"),
    ("MQ", "MTQ"),
    ("MR", "MRT"),
    ("MS", "MSR"),
    ("MT", "MLT"),
    ("MU", "MUS"),
    ("MV", "MDV"),
    ("MW", "MWI"),
    ("MX", "MEX"),
    ("MY", "MYS"),
    ("MZ", "MOZ"),
    ("NA", "NAM"),
    ("NC", "NCL"),
    ("NE", "NER"),
    ("NG", "NGA"),
    ("NI", "NIC"),
    ("NL", "NLD"),
    ("NO", "NOR"),
    ("NP", "NPL"),
    ("NR", "NRU"),
    ("OM", "OMN"),
    ("PA", "PAN"),
    ("PE", "PER"),
    ("PH", "PHL"),
    ("PK", "PAK"),
    ("PL", "POL"),
    ("PT", "PRT"),
    ("PY", "PRY"),
    ("QA", "QAT"),
    ("RO", "ROU"),
    ("RS", "SRB"),
    ("RU", "RUS"),
    ("RW", "RWA"),
    ("SA", "SAU"),
    ("SB", "SLB"),
    ("SC", "SYC"),
    ("SD", "SDN"),
    ("SE", "SWE"),
    ("SG", "SGP"),
    ("SI", "SVN"),
    ("SK", "SVK"),
    ("SL", "SLE"),
    ("SM", "SMR"),
    ("SN", "SEN"),
    ("SO", "SOM"),
    ("SR", "SUR"),
    ("SS", "SSD"),
    ("ST", "STP"),
    ("SV", "SLV"),
    ("SX", "SXM"),
    ("SY", "SYR"),
    ("SZ", "SWZ"),
    ("TD", "TCD"),
    ("TG", "TGO"),
    ("TH", "THA"),
    ("TJ", "TJK"),
    ("TL", "TLS"),
    ("TN", "TUN"),
    ("TO", "TON"),
    ("TR", "TUR"),
    ("TT", "TTO"),
    ("TZ", "TZA"),
    ("UA", "UKR"),
    ("UG", "UGA"),
    ("US", "USA"),
    ("UY", "URY"),
    ("UZ", "UZB"),
    ("VC", "VCT"),
    ("VE", "VEN"),
    ("VG", "VGB"),
    ("VN", "VNM"),
    ("WS", "WSM"),
    ("YE", "YEM"),
    ("ZA", "ZAF"),
    ("ZM", "ZMB"),
    ("ZW", "ZWE"),
];
